AWSTemplateFormatVersion: '2010-09-09'
Description: 'EventBridge scheduler for GuardDuty enablement'

Parameters:
  ScheduleExpression:
    Type: String
    Default: 'rate(7 days)'
    Description: 'EventBridge schedule expression'

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: GuardDutyFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - guardduty:*
                  - ec2:DescribeRegions
                Resource: '*'

  GuardDutySchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt GuardDutyLambdaFunction.Arn

  GuardDutyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: aws-security-toolkit-guardduty
      Runtime: python3.9
      Handler: aws_sec_toolkit.lambda_handlers.handler_guardduty.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          # Placeholder - replace with actual deployment package
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Not implemented'}
      Timeout: 300

  GuardDutyScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: 'Scheduled GuardDuty enablement'
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt GuardDutyLambdaFunction.Arn
          Id: GuardDutyTarget

  GuardDutyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GuardDutyLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt GuardDutyScheduleRule.Arn

Outputs:
  LambdaFunctionArn:
    Description: 'GuardDuty Lambda Function ARN'
    Value: !GetAtt GuardDutyLambdaFunction.Arn